#cloud-config
package_update: true
package_upgrade: true
packages:
  iptables-persistent
write_files:
  - path: /root/cloudinit
    content: |
      test
  - path: /etc/sysctl.d/99-nat.conf
    content: |
      net.ipv4.ip_forward=1
  - path: /etc/iptables/rules.v4
    content: |
      *filter
      :INPUT ACCEPT [0:0]
      :FORWARD ACCEPT [0:0]
      :OUTPUT ACCEPT [0:0]
      -A FORWARD -i ens10 -o eth0 -j ACCEPT
      -A FORWARD -i eth0 -o ens10 -m state --state RELATED,ESTABLISHED -j ACCEPT
      COMMIT
      *nat
      :PREROUTING ACCEPT [0:0]
      :INPUT ACCEPT [0:0]
      :OUTPUT ACCEPT [0:0]
      :POSTROUTING ACCEPT [0:0]
      -A POSTROUTING -o eth0 -j MASQUERADE
      COMMIT

runcmd:
  - sysctl --system
